# **02_Tensors**

## **a_tensor_initialization.py**

tensor란? 다차원 배열 객체

In [1]:
import torch

In [2]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)  
print(t1.device) 
print(t1.requires_grad)  
print(t1.size())  
print(t1.shape)   

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


텐서 생성 및 데이터 타입, 장치, 기울기 계산 필요, 크기 출력

In [3]:
t1_cpu = t1.cpu()

print("#" * 50, 1)

################################################## 1


In [4]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype) 
print(t2.device) 
print(t2.requires_grad) 
print(t2.size()) 
print(t2.shape)  

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


t2 텐서 생성

In [5]:
t2_cpu = t2.cpu()

print("#" * 50, 2)

################################################## 2


In [6]:
a1 = torch.tensor(1)			   
print(a1.shape, a1.ndim)

torch.Size([]) 0


0차원 텐서 a1 생성<br>형태 및 차원 반환 (0차원)

In [7]:
a2 = torch.tensor([1])		  	     
print(a2.shape, a2.ndim)

torch.Size([1]) 1


1차원 텐서 a2 생성<br>
형태 및 차원 반환 (1차원)

In [8]:
a3 = torch.tensor([1, 2, 3, 4, 5])   
print(a3.shape, a3.ndim)

torch.Size([5]) 1


5개 요소 지닌 1차원 텐서 a3 생성

In [9]:
a4 = torch.tensor([[1], [2], [3], [4], [5]]) 
print(a4.shape, a4.ndim)

torch.Size([5, 1]) 2


5행 1열의 2차원 텐서 a4 생성

In [10]:
a5 = torch.tensor([              
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


3행 2열의 2차원 텐서 a5 생성

In [11]:
a6 = torch.tensor([               
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

torch.Size([3, 2, 1]) 3


3개의 2차원 배열을 지닌 3차원 텐서 a6 생성

In [12]:
a7 = torch.tensor([               
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

torch.Size([3, 1, 2, 1]) 4


3개의 3차원 배열을 지닌 4차원 텐서 a7 생성

In [13]:
a8 = torch.tensor([                
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

torch.Size([3, 1, 2, 3]) 4


3개의 3차원 배열을 지닌 4차원 텐서 a8 생성

In [14]:
a9 = torch.tensor([                
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

torch.Size([3, 1, 2, 3, 1]) 5


3개의 4차원 배열 갖는 텐서 a9 생성

In [15]:
a10 = torch.tensor([               
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

torch.Size([4, 5]) 2


2차원 텐서 a10 생성

In [16]:
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

ValueError: expected sequence of length 3 at dim 3 (got 2)

내부 리스트의 길이가 달라 오류 발생


==========================================================================================<br>
ex)
```python
a8 = torch.tensor([                
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


>>> torch.Size([3, 1, 2, 1]) 4 
```

의미 : 첫번째 차원에 3개의 요소, 두번째 차원에 1개의 요소, 3번째 차원에 2개의 요소, 4번째 차원에 1개의 요소, 4차원

## **b_tensor_initialization_copy.py**

In [ ]:
import torch
import numpy as np

In [ ]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1) # float32 데이터 타입의 텐서 생성

l2 = [1, 2, 3]
t2 = torch.tensor(l2) # int64 데이터 타입의 텐서 생성

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) # 데이터를 텐서로 변환

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)

생성시 새로운 메모리에 데이터 할당(메모리 참조 x)<br>
Tensor() => float32 데이터 타입의 텐서 생성 <br>
tensor() => int64 데이터 타입의 텐서 생성 



In [ ]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

numpy를 지닐땐 as_tenser 이용하여 바로 참조 가능 t6만 값이 바뀜

## **c_tensor_initialization_constant_values.py**

In [ ]:
import torch

In [ ]:
t1 = torch.ones(size=(5,)) 
t1_like = torch.ones_like(input=t1)
print(t1) 
print(t1_like)  

데이터를 일일이 채울 필요 없음<br>
torch.ones(size) => size 만큼 1로 채워진 텐서 반환<br>
torch.ones_like(input) => input 텐서와 같은 사이즈 만큼의 1로 채워진 텐서 반환

In [ ]:
t2 = torch.zeros(size=(6,))  
t2_like = torch.zeros_like(input=t2)
print(t2)  
print(t2_like) 

torch.zeros(size) => size 만큼 0으로 채워진 텐서 반환<br>
torch.zeros_like(input) => input 텐서와 같은 사이즈 만큼의 0로 채워진 텐서 반환

In [ ]:
t3 = torch.empty(size=(4,))  
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like) 

torch.empty(size) => 초기화 하지 않고 size 만큼의 텐서 생성, 메모리 절약 및 빠름<br>
torch.empty_like(input) =>  input 텐서와 같은 사이즈 만큼의 초기화 되지 않은 텐서 반환

In [ ]:
t4 = torch.eye(n=3)
print(t4)

torch.eye(n) => 대각선이 1인, n x n 텐서 반환

## **d_tensor_initialization_random_values.py**

In [ ]:
import torch

In [ ]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

print("#" * 30)

torch.randint(low, high, size) => size 만큼의 low ~ high 정수형 랜덤값 갖는 텐서 반환<br><br>
torch.rand(size) => size 만큼의 0 ~ 1 사이 균등 분포 랜덤 실수 갖는 텐서 반환<br><br>
torch.randn(size) => size 만큼의 평균 0, 표준편차 1인 정규 분포 실수 랜덤값 갖는 텐서 반환<br><br>
torch.normal(mean, std, size) => 주어진 평균(mean)과 표준 편차(std)를 가지는 정규 분포에서 랜덤한 실수 값을 가지는 텐서를 생성<br><br>
torch.linspace(start, end, steps) => start에서 end까지의 구간을 steps 개수만큼 균등하게 나눈 값을 가지는 텐서를 생성<br><br>
torch.arange(start = 0, end, step = 1) => start부터 end까지 step 간격으로 값을 가지는 텐서를 생성

In [ ]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

torch.manual_seed() => 랜덤 생성의 시드 설정 <br> 동일한 시드값을 이용했기떄문에 random1, random2 // random3, random4 값이 같음

## **e_tensor_type_conversion.py**

In [ ]:
import torch

a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

torch.ones() 텐서 생서 및 초기화(1), 자료형은 float32 <br>
인자로 dtype => 자료형 지정<br>
.to 로 자료형 변경 가능

In [ ]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

인자로 dtype = double, .double(), .to(torch.double) 모두 데이터 타입 지정

In [ ]:
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

double로 변환되어 연산 수행

## **f_tensor_operations.py**

In [ ]:
import torch

t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

요소별 덧셈 / .add(), + 결과 같음

In [ ]:
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

요소별 덧셈 / .sub(t1, t2), t1 - t2  결과 같음

In [ ]:
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

요소별 곱셈 / .mul(t1, t2), t1 * t2 결과 같음

In [ ]:
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

요소별 곱셈 / .div(t1, t2), t1 / t2 결과 같음

torch.add(), torch.sub(), torch.mul(), torch.div() 함수와 각각의 연산자(+, -, *, /) 간 결과 같음

## **g_tensor_operations_mm.py**

In [ ]:
import torch

t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

.dot(input, other) => 내적 계산, 대응하는 요소끼리 곱한 값들의 합<br|>
[2, 3]과 [2, 1]의 내적은 (2 * 2) + (3 * 1)로 계산되어 7

In [ ]:
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

.mm(input, other) => 행렬 곱셈

In [ ]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())

.bmm(input, other) => 배치 행렬 곱셈 / 배치 -> 제일 처음 차원, 배치는 살려두고 연산

## **h_tensor_operations_matmul.py** <br> 

In [ ]:
import torch

t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

dot product 수행

In [ ]:
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

In [ ]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

In [ ]:
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

In [ ]:
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])  설명

**torch.matmul() => 입력 텐서의 차원에 따라 dot, mm, bmm 수행**

## **i_tensor_broadcasting.py**

In [ ]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

텐서의 각 요소에 스칼라(t2) 곱해짐

In [ ]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

브로드캐스팅 되어 연산 수행, 큰쪽으로 맞춰짐

In [ ]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0) 
print(t5 - 2.0)  
print(t5 * 2.0) 
print(t5 / 2.0)  

print("#" * 50, 3)

In [ ]:
def normalize(x):
    return x / 255
t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

```python
def normalize(x):
    return x / 255
```
0과 255 사이에 있던 데이터들이 0과 1사이로 맞춰짐 브로드캐스팅 통해 연산

In [ ]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])

print(t7 + t8)  
print(t7 + t9)   
print(t8 + t9)   
print(t7 + t10)

print("#" * 50, 5)

브로드캐스팅에 따라 연산이 이루어짐(큰쪽에 맞춰짐)

In [ ]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 차원 없으면 생성, 순서는 마지막 부터 처음으로
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1) 
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  
print((t17 + t18).size())

print("#" * 50, 6)

차원 없으면 생성 / 1이 큰 쪽에 맞춰짐

In [ ]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

위와 마찬가지

In [ ]:
t25 = torch.empty(5, 2, 4, 1)
t26 = torch.empty(3, 1, 1)
print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

t26 일치하지 않는 차원 중 하나가 1이 아니라 오류

In [ ]:
print("#" * 50, 7)

In [ ]:
t27 = torch.ones(4) * 5
print(t27)  

t28 = torch.pow(t27, 2) # 제곱
print(t28) 

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp) # shape이 맞는걸 넣음
print(t29) 


## **j_tensor_indexing_slicing.py**

In [ ]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

: => 전체

In [ ]:
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

In [ ]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

In [ ]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

**파이썬 인덱싱과 슬라이싱과 비슷, 크게 다르지 않음**

## **k_tensor_reshaping.py**

**텐서 shape을 바꿈**

In [ ]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2) 
t3 = t1.reshape(1, 6) 
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4) 
t5 = torch.arange(6).view(2, 3) 
print(t4)
print(t5)

print("#" * 50, 1)

torch.view(input, *shape), torch.reshape(input, *shape)<br>
데이터를 건들지 않고 텐서의 shape만 바꿈

view 연속적인 텐서 shape 변경, 참조<br>
reshape 연속적이지 않아도 shaep 변경, 복사

torch.arange().view() => 다차원 텐서 생성 가능

In [ ]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

tensor.squeeze() 크기가 1인 모든 차원 제거, tensor.squeeze(0) 0번째 차원만 제거

In [17]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3


tensor.unsqueeze(1)은 1번 차원에 새 차원을 추가


In [18]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4


`tensor.flatten()` 다차원 array를 1차원 array로 변환<br>
t17 = `torch.flatten(t15, start_dim=1)` => 특정 차원을 정한다면 특정 차원은 남아있게됨

In [19]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >|>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


torch.permute() 차원은 유지하고 차원의 순서를 바꿈


torch.transpose() 두 개의 차원 지정해서 두개의 차원 순서 변경

## **l_tensor_concat.py**

In [20]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

print("#" * 50, 1)

torch.Size([2, 6, 3])
################################################## 1


`torch.cat` 텐서들을 지정된 차원 따라 연결하여 새로운 텐서 생성

In [21]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2


1차원 텐서 t5와 t6을 dim=0 차원 따라 연결, 요소 8개 가진 1차원 텐서 t7 생성

In [22]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)

print("#" * 50, 3)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3


2차원 텐서 t8과 t9를 dim=0 / dim=1 차원 따라 연결하여, [4, 3] 크기의 t10,  [2, 6] 크기의 t11 텐서 생성

In [23]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)

print("#" * 50, 4)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4


세 개의 2차원 텐서(t12, t13, t14)를 dim=0으로 연결하여 [6, 3] 크기의 t15, dim=1로 연결하여 [2, 9] 크기의 t16 생성

In [24]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


마찬가지로 주어진 차원 따라 연결해 새로운 텐서 생성

## **m_tensor_stacking.py**

In [25]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1


`torch.stack()`텐서들을 주어진 차원을 따라 쌓아 하나의 텐서로 결합, 새로운 차원으로 확장

`torch.stack` `torch.cat(unsqueeze())` 결과 같음

In [26]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))


t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))


torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


위와 마찬가지

## **n_tensor_vstack_hstack.py**

In [27]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

t9 = torch.vstack([t7, t8])
print(t9.shape)

print(t9)

print("#" * 50, 1)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1


`torch.vstack(t1, t2)` 수직으로 쌓아서 텐서를 생성

In [28]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)


t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)


t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)


t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)


t18 = torch.hstack([t16, t17])
print(t18.shape)


print(t18)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


`torch.hstack(t1, t2)` 수평으로 쌓아서 텐서를 생성

## **숙제 후기**

_02_Tensors는 텐서를 다루는걸 익히는 챕터였다. 텐서, 무엇보다 차원을 이해하는것이 가장 중요하다고 생각되며 각 연산들은 차원만 이해한다면 어떻게 동작하는지 알 수 있다고 생각되며 확실하게 짚고 넘어가야 추후 어려움이 없을것같다.